module.exports = {
  SHOW_TOAST: 'SHOW_TOAST',
  HIDE_TOAST: 'HIDE_TOAST',
  SHOW_LOADING: 'SHOW_LOADING',
  HIDE_LOADING: 'HIDE_LOADING',
  SET_WINDOW_SIZE: 'SET_WINDOW_SIZE',
  SHOW_ADD_WEBSITE: 'SHOW_ADD_WEBSITE',
  HIDE_ADD_WEBSITE: 'HIDE_ADD_WEBSITE'
};
